# Generated by Django 3.0.6 on 2020-06-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
